### ISSUE TITLE
Bootstrap module doesn't load

### ISSUE THREAD

**Issue by igrowing** [igrowing/Orchids#1]
```
$ m runserver 0.0.0.0:8001
Unhandled exception in thread started by <function wrapper at 0x761137f0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named bootstrap3


```

**Comment by igrowing** [comment]
pip install django-bootstrap3
Plus unpack the boostrap archive into orchid_app/static/bootstrap/

Now failing at 
NoReverseMatch at /

**Comment by igrowing** [comment]
Bootstrap loaded. Not used thus.
